config/routes.rb
Rails.application.routes.draw do
    root 'teams#start'

    get 'draw_teams', to: 'teams#draw_teams'
    get 'generate_results', to: 'matches#generate_results'
    get 'show', to: 'matches#show'
    post 'new', to: 'teams#new'
    post 'autogenerate_divisions', to: 'teams#autogenerate_divisions'
    post 'generate_divisions', to: 'teams#generate_divisions'
    post 'generate_results', to: 'matches#generate_results'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :team

  enum :game, { draw: 0, match_one: 1, match_two: 2, playoff_one: 3, playoff_final: 4 }
  enum :status, { win: 1, defeat: 0 }

  class << self
    def game_data
      reset_matches if playoff_final?
      create_initial_matches unless exists?
      { teams: winning_teams, stage: next_stage }
    end

    def next_stage
      games.key(current_stage_value + 1)
    end

    def current_stage_value
      games[last.game]
    end

    def create_initial_matches
      Team.all.each { |mate| Match.create(team: mate, game: :draw) }
    end

    def winning_teams
      Team.joins(:matches).where(matches: { game: current_stage_value, status: :win })
    end

    def record_result(winner, defeat, stage)
      create(team: winner, game: stage, status: :win)
      create(team: defeat, game: stage, status: :defeat)
    end

    def reset_matches
      destroy_all
    end

    def playoff_final?
      last&.playoff_final?
    end
  end
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :matches, dependent: :destroy

  validates :name, presence: true, uniqueness: true
  validates :score, presence: true, numericality: true
  validates :division, format: { with: /\A[A|B]?\z/,
                                    message: "%{value} is not a division A or B" }

  class << self
    def autogenerate_division
      Team.destroy_all
      16.times(&method(:team_autogenerate))
    end

    def team_autogenerate(number)
      Team.create(name: Faker::Sports::Football.unique.team, division: number < 8 ? 'A' : 'B')
    end
  end

  def add_score
    update(score: diff_score)
  end

  def diff_score
    score + rand(1..10)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  def generate_results
    match = Match.game_data
    Game.create(match)
    redirect_to :show, notice: "Result for #{match[:stage].humanize}"
  end

  def show
    @teams = Match.winning_teams
    @stage = Match.last
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def start; end

  def new
    @team_a, @team_b = Array.new(16) { Team.new }.each_slice(8).to_a
    flash.now[:message] = 'The team division is already established !!!' if Team.exists?
  end

  def draw_teams
    @teams = Team.all
  end

  def autogenerate_divisions
    Team.autogenerate_division
    redirect_to draw_teams_path, notice: 'Divisions have been successfully autogenerated.'
  end

  def generate_divisions
    team_params[:teams_attributes].each_value { |team_attributes| Team.create(team_attributes) }
    redirect_to draw_teams_path, notice: 'Divisions have been successfully created.'
  end

  def team_params
    params.require(:team).permit(teams_attributes: %i[name division])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tournament</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/flash" %>
    <%= yield %>
  </body>
</html>

app/views/matches/_results.html.slim
tr
  td
    = team.name
  td
    = team.division
  td
    = team.score

app/views/matches/show.html.slim
table style="text-align:center"
  tr
    th
      |Name team
    th
      |  Division
    th
      |  Score
    = render partial: 'results', collection: @teams, as: :team
br
- if @stage.playoff_final?
  = button_to 'Go start page', root_path, method: :get
- else
  = button_to 'Next', generate_results_path, method: :get

app/views/shared/_flash.html.slim
- flash.each do |key, msg|
  = content_tag :div, msg, :id => "flash_#{key}"